# Generated by Django 4.0.4 on 2022-05-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statia_title', models.CharField(max_length=250, verbose_name='Название статьи')),
                ('html_texst', models.TextField(verbose_name='Код')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('model_img', models.ImageField(upload_to='static/img')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Автор')),
                ('comment_text', models.TextField(max_length=5000, verbose_name='Текст коментариия')),
                ('name_stati', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poteri.statia')),
            ],
        ),
    ]
